version: '3.0'
volumes:
  node_dev:
  angular_dev:
  flutter_dev:
  python_dev:
  java_dev:
  go_dev:
  my_db:
  dbeaver_data:
services:
  node-16:
    build:
      context: .
      dockerfile: docker/Dockerfile.node-16
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - node_dev:/home/dev/source
  angular-14:
    build:
      context: .
      dockerfile: docker/Dockerfile.angular-14
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - angular_dev:/home/dev/source
  flutter-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.flutter-3
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - flutter_dev:/home/dev/source
  python-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.python-3
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - python_dev:/home/dev/source
  node-20:
    build:
      context: .
      dockerfile: docker/Dockerfile.node-20
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - node_dev:/home/dev/source
  jdk-17:
    build:
      context: .
      dockerfile: docker/Dockerfile.jdk-17
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - java_dev:/home/dev/source
  go-19:
    build:
      context: .
      dockerfile: docker/Dockerfile.go-19
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - go_dev:/home/dev/source
  node-20-slim:
    build:
      context: .
      dockerfile: docker/Dockerfile.node-20-slim
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - node_dev:/home/dev/source
  mydb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - my_db:/var/lib/mysql
  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    ports:
      - 8978:8978
  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411
  elk:
    build:
      context: .
      dockerfile: docker/Dockerfile.elk
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=1G
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.system_call_filter= true
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044

