FROM ubuntu:22.04
ENV PATH="$PATH:/home/flutter/bin"
WORKDIR /home
RUN apt update
RUN apt upgrade -y
RUN apt install curl unzip zip xz-utils git -y
RUN git clone https://github.com/flutter/flutter.git -b stable
RUN flutter precache 